# Site settings
title: Formeo
email: j.tobiasandersen@gmail.com   
description: > # this means to ignore newlines until "baseurl:"
    Additive manufacturing
baseurl: "/formeo" # the subpath of your site, e.g. /blog/
url: "http://formeo.se" # the base hostname & protocol for your site
twitter_username: tobiasandersen
github_username:  tobiasandersen

exclude: [Gruntfile.js, package.json, js-source] 

# Build settings
markdown: kramdown

